@startuml

skin rose

Title: Sem cache

actor "Usuário" as actor
interface "Browser" as browser


actor -> browser


component "Backend\n" {

  node SSR
  node "api" as backend
  node reviewGateway as reviewGateway
  node studentGateway as studentGateway
  database database

  browser -> SSR
  backend --> database: 70ms
  backend --> database: 30ms
  backend --> reviewGateway: 100ms
  backend --> studentGateway: 300ms

}

SSR -> backend: 520ms
note right of backend: +20ms (Interno)

@enduml