@startuml

skin rose

Title: Grande lançamento (centenas/milhares de usuários)

interface "Browser" as browser

component "Backend\n" {

  node SSR
  node "api" as backend #aqua
  node reviewGateway as reviewGateway
  node studentGateway as studentGateway
  database database
  database redis as redis  #red

    SSR --> backend
    SSR --> backend
    SSR --> backend
    SSR --> backend
    SSR --> backend
    SSR --> backend
    SSR --> backend

  backend -> redis
  backend -> redis
  backend -> redis
  backend -> redis
  backend -> redis
  backend -> redis
  backend -> redis

  backend --> database: 0
  backend --> database: 0
  backend --> reviewGateway: 0
  backend --> studentGateway #red: 0

  note left of backend: Todos acessando o mesmo conteúdo
}

rectangle "Browsers\n" {
    (b1) --> SSR
    (b2) --> SSR
    (b3) --> SSR
    (b4) --> SSR
    (b5) --> SSR
    (b6) --> SSR
    (b7) --> SSR
}









@enduml