@startuml

skin rose

Title: Com cache parcial

component "LB Front" as LBF
component "LB Back" as LBB
actor "Usuário" as actor
database database
interface "Browser" as browser
node frontend
node backend
node reviewGateway as "ReviewGateway"
node studentGateway as "StudentGateway" #red

actor -> browser
browser -> LBF
LBF -> frontend
frontend -> LBB
LBB -> backend : 500 -> 101ms
note right of backend: +20ms outros processamentos
backend --> reviewGateway: 10ms
backend --> studentGateway : 10ms
backend ..> database: 70ms
backend ..> database: 1ms

@enduml