@startuml

skin rose

Title: Cache dos componentes envolvidos

actor "Usuário" as actor
interface "Browser" as browser

component "Backend\n" {

  
  node SSR
  node "api" as backend
  node reviewGateway as reviewGateway #aqua
  node studentGateway as studentGateway #aqua
  database database #aqua
  database redis as redis  #red

  actor -> browser
  browser -> SSR
  backend -> redis: Existe?Armazena
  backend --> database: 1ms
  backend --> database: 0ms ()
  backend --> reviewGateway: 10ms
  backend --> studentGateway: 10ms
}

SSR -> backend: 520 -> 51ms
note top of backend: +20ms (Interno)

@enduml