@startuml

skin rose

Title: Cache apenas do gateway mais lento


actor "Usuário" as actor
interface "Browser" as browser

component "Backend\n" {

  node SSR
  node "api" as backend
  node reviewGateway as reviewGateway
  node studentGateway as studentGateway #aqua
  database database
  database redis as redis  #red

  actor -> browser
  browser -> SSR
  backend -> redis: Existe?Armazena
  backend --> database: 70ms
  backend --> database: 30ms
  backend --> reviewGateway: 100ms
  backend --> studentGateway #red: 10ms

}

SSR -> backend: 520 -> 230ms
note top of backend: +20ms (Interno)

@enduml