@startuml

skin rose

Title: Usando CDN: Content Delivery Network (ou Rede de Distribuição de Conteúdo)

actor "Usuário" as actor
interface "Browser" as browser
node CDN as cdn #yellow

actor -> browser
browser -> cdn

component "Backend\n" {

  node SSR
  node "api" as backend
  node reviewGateway as reviewGateway
  node studentGateway as studentGateway
  database database

  cdn -> SSR: 0
  SSR -> backend: 0
  backend --> database
  backend --> database
  backend --> reviewGateway
  backend --> studentGateway
}

note bottom of cdn: Cache na ponta, evita todo o fluxo.


@enduml