@startuml

skin rose

Title: Fluxo com alguns componentes omitidos

actor "Usuário" as actor
interface "Browser" as browser
node frontend

actor -> browser
browser -> frontend

component "Backend\n" {

  node "apiBackend" as backend
  node reviewGateway as reviewGateway
  node studentGateway as studentGateway
  database database

  backend --> database: 70ms
  backend --> database: 30ms
  backend --> reviewGateway: 100ms
  backend --> studentGateway #red: 300ms
}

frontend -> backend: 520ms
note top of backend: +20ms (Interno)

@enduml