@startuml

skin rose

Title: Com cache completo

component "LB Front" as LBF
component "LB Back" as LBB
actor "Usuário" as actor
database database
interface "Browser" as browser
node frontend
node backend
node outroBackend as "PlatformGateway"
node outroBackend2 as "StudentGateway" #red

actor -> browser
browser -> LBF
LBF -> frontend
frontend -> LBB
LBB -> backend : 500 -> 91ms
backend --> outroBackend: 100 -> 10ms
backend --> outroBackend2 : 300 -> 10ms
backend ..> database: 100 -> 71ms

@enduml