@startuml

skin rose

Title: Cache dos componentes envolvidos

actor "Usuário" as actor
interface "Browser" as browser

component "Backend\n\n" {
  
  node SSR
  node "api" as backend
  node reviewGateway as reviewGateway #aqua
  node studentGateway as studentGateway #aqua
  database database #aqua
  database redis as redis  #red

  actor -> browser
  browser -> SSR
  backend --> redis
  backend --> redis
  backend --> redis
  backend --> redis

  note left of redis
    reviewGateway   : 100 -> 2ms

    studentGateway  : 100 -> 2ms

    database        : 100 -> 2ms
  end note

  redis ..> database: X
  redis ..> database: X
  redis ..> reviewGateway: X
  redis ..> studentGateway: X
}

SSR -> backend: 520 -> 26ms
note right of backend: +20ms (Interno)

@enduml