@startuml

skin rose

Title: Fluxo com alguns componentes omitidos

component "LB Front" as LBF
component "LB Back" as LBB
actor "Usuário" as actor
database database
interface "Browser" as browser
node frontend
node backend
node reviewGateway as "ReviewGateway"
node studentGateway as "StudentGateway" #red

actor -> browser
browser -> LBF
LBF -> frontend
frontend -> LBB
LBB -> backend : 520ms
note right of backend: +20ms outros processamentos
backend --> reviewGateway: 100ms
backend --> studentGateway : 300ms
backend ..> database: 70ms
backend ..> database: 30ms

@enduml