@startuml

skin rose

Title: Cache na entrada do endpoint

actor "Usuário" as actor
interface "Browser" as browser


component "Backend\n" {

  node SSR
  node "api" as backend #aqua
  node reviewGateway as reviewGateway
  node studentGateway as studentGateway
  database database
  database redis as redis  #red

  actor -> browser
  browser -> SSR
  backend -> redis: Existe? (10ms)
  backend --> database: 0
  backend --> database: 0
  backend --> reviewGateway: 0
  backend --> studentGateway: 0
}

SSR -> backend: 520 -> 30ms
note top of backend: +20ms (Interno)

@enduml