@startuml

skin rose

Title: Cache parcial


actor "Usuário" as actor
interface "Browser" as browser

component "Backend\n" {

  node SSR
  node "api" as backend
  node reviewGateway as reviewGateway #aqua
  node studentGateway as studentGateway #aqua
  database database
  database redis as redis  #red


  actor -> browser
  browser -> SSR
  backend --> redis
  backend --> redis
  backend --> redis
  backend --> redis

  note left of redis
   reviewGateway  : 100 -> 2ms

   studentGateway : 300 -> 2ms
  end note

  redis ..> reviewGateway: X
  redis ..> studentGateway #red: X
  redis --> database: 70ms
  redis --> database: 30ms

  note left of database
     Para ganhar ese tempo
     no database seria interessante
     usar um evict de trigger.
    end note




}

SSR -> backend: 520 -> 124ms
note right of backend: +20ms (Interno)

@enduml