@startuml

skin rose

Title: Grande lançamento (centenas/milhares de usuários)

component "Backend\n" {

  node SSR
  node "api" as backend #aqua
  node reviewGateway as reviewGateway
  node studentGateway as studentGateway
  database database
  database redis as redis  #red

    SSR -> backend
    note left of SSR: Acesso ao mesmo produto
    SSR -> backend
    SSR -> backend
    SSR -> backend
    SSR -> backend

  backend --> redis
  backend --> redis
  backend --> redis
  backend --> redis
  backend --> redis


  redis ..> database: X
  redis ..> database: X
  redis ..> reviewGateway: X
  redis ..> studentGateway #red: X

  note left of redis: Resposta do cache: 2ms
}

rectangle "Browsers\n" {
    (b1) --> SSR
    (b2) --> SSR
    (b3) --> SSR
    (b4) --> SSR
    (b5) --> SSR
    (b6) --> SSR
    (bN) --> SSR
}

@enduml