@startuml

skin rose

Title: Cache apenas do gateway mais lento


actor "Usuário" as actor
interface "Browser" as browser

component "Backend\n" {

  node SSR
  node "api" as backend
  node reviewGateway as reviewGateway
  node studentGateway as studentGateway #aqua
  database database
  database redis as redis  #red


  actor -> browser
  browser -> SSR
  backend --> redis
  backend --> redis
  backend --> redis
  backend --> redis

  note left of redis
   studentGateway  : 300 -> 2ms
  end note

  redis --> database: 70ms
  redis --> database: 30ms
  redis --> reviewGateway: 100ms
  redis ..> studentGateway #red: X

}

SSR -> backend: 520 -> 222ms
note right of backend: +20ms (Interno)

@enduml