@startuml

skin rose

Title: Usando CDN: Content Delivery Network (ou Rede de Distribuição de Conteúdo)

actor "Usuário" as actor
interface "Browser" as browser
node CDN as cdn #yellow

actor -> browser
browser -> cdn

component "Backend\n" {

  node SSR
  node "api" as backend
  node reviewGateway as reviewGateway
  node studentGateway as studentGateway
  database database

  cdn -> SSR: X
  SSR -> backend: X
  backend ..> database: X
  backend ..> database: X
  backend ..> reviewGateway: X
  backend ..> studentGateway: X
}

note bottom of cdn: Cache na ponta, evita todo o fluxo.

@enduml